### PR TITLE
Scripting Examples

### PR DESCRIPTION
**Pull request by bnorthan**
@ctrueden, @hinerm 

In preparation for the OPS workshop (and beyond) I created jython and groovy directories for scripting examples. 

I then converted the LoadAndDisplayDataset example to both a jython and a groovy script. 

I plan to put a few more OPS scripting examples here.  Let me know if you guys are OK with the directory structure.

### CODE REVIEW

**Comment by bnorthan** [comment]
@ctrueden, @hinerm 

I've added a couple of image processing examples to the 'jython' and 'groovy' directories.  Findtemplates.groovy is based on one of the imglib2 fft examples (http://fiji.sc/ImgLib2_Examples#Example_6c_-_Complex_numbers_and_Fourier_transforms
).  

The only issue I found using groovy was with arrays, long[] seems to get converted to (Long, Long).  

the following code does not seem to work...

``` java
 templateInverse=ops.create().img([template.dimension(0), template.dimension(1)])
```
nor does this...

``` java
size=new long[template.numDimensions()]

for (int i=0;i<template.numDimensions();i++) {
	size[i]=template.dimension(i);
}

templateInverse=ops.create().img(size)
```

**Comment by ctrueden** [comment]
I'll be digging into this more today and tomorrow, with the goal of getting it merged ASAP.

But one quick question: does anything actually require those images to be committed to Git? I'd rather avoid that if possible, so the repository doesn't bloat in size. We can instead use an "Open Samples" style approach that reads images on demand off the network. Looking at the scripts, I didn't see any references to the test images—did I miss it?

**Comment by bnorthan** [comment]
Hi Curtis - there is no reason the images need to be committed to git.  

It would be fine to use "Open Samples" style.   In that case where do the images go??

**Comment by ctrueden** [comment]
OK, I pushed the commits that add images to [their own branch](https://github.com/imagej/imagej-tutorials/compare/images) for now. Probably will delete that branch without merge, but not until those images are secured at some stable URL online first.

**Comment by dscho** [comment]
> It would be fine to use "Open Samples" style. In that case where do the images go??

@bnorthan You need to use Fiji's `Help>Open Sample Image` option, and then @ctrueden needs to use the http://fiji.sc/Special:Incoming page to promote them. After that, you need to patch https://github.com/fiji/Samples/blob/master/src/main/resources/plugins.config to add the menu entries.

**Pull request merged**
