### PR TITLE
More scripts (in progress...)

### PR DESCRIPTION
**Pull request by bnorthan**
@ctrueden 

The pull request adds a groovy version of UsingOps, and IntroToImageJAPI, that could be used in the workshop.  I need to test with and sync to @hinerm's latest changes to sci-java/imagej-ops.  I also want to make jython versions. 

Let me know if either of you have any comments.

### CODE REVIEW

**Comment by ctrueden** [comment]
Seems great! There are certainly small cleanups I'll do in the next few days, but LGTM to me. :+1: Unless you want to wait for some reason?

**Comment by bnorthan** [comment]
@ctrueden feel free to cleanup and move things around as needed.  I also am working on slides, however when I tried to push my branch to the presentations repo it gave me a permission denied error.

**Comment by ctrueden** [comment]
Oops, sorry @bnorthan. There were a couple of repositories not included on the "ImageJ2 Developers" team. I have now remedied that, so pushing to presentations should work.

**Comment by ctrueden** [comment]
Just getting stuff onto master as soon as possible. We'll continue to iterate on these, of course.

**Pull request merged**
